sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: "YOUR_ACCESS_KEY_ID" # 替换为实际的AccessKeyId
    access-key-secret: "YOUR_ACCESS_KEY_SECRET" # 替换为实际的AccessKeySecret
    bucket-name: sky-ahut
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: YOUR_APPID # 替换为实际的APPID
    secret: YOUR_SECRET # 替换为实际的SECRET
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://275c7d4b.r23.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://275c7d4b.r23.cpolar.top/notify/refundSuccess